CREATE EXTENSION IF NOT EXISTS CITEXT;
CREATE EXTENSION IF NOT EXISTS PGCRYPTO;

DROP TABLE IF EXISTS auths;

CREATE TABLE auths (
   id BIGSERIAL PRIMARY KEY NOT NULL,
   pass TEXT NOT NULL,
   email CITEXT NOT NULL UNIQUE,
   email_verification_code TEXT NOT NULL,
   is_email_verified BOOLEAN NOT NULL
);
